# Generated by Django 4.1 on 2025-04-02 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuari',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('correu', models.EmailField(max_length=254, unique=True)),
                ('contrasenya', models.CharField(max_length=100)),
                ('data_creacio', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
